backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'titre', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Cover', name: 'couverture', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }