backend:
  name: git-gateway
  branch: master

# local_backend: true

media_folder: static/img
public_folder: /img

media_library:
  name: cloudinary
  config:
    cloud_name: genesi-communication-design
    api_key: 712811648934331

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    format: 'frontmatter'
    create: true
    identifier_field: titre
    sortable_fields: ['date', 'titre']
    slug: "{{titre}}"
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'titre', widget: 'string' }
      - { label: 'Vedette', name: 'vedette', widget: 'boolean', required: false, default: false}
      - { label: 'Date', name: 'date', widget: 'datetime', date_format: 'DD-MM-YYYY', time_format: false }
      - { label: 'URL', name: 'url', widget: 'string', required: false }
      - { label: 'Auteur', name: 'auteur', widget: 'string', required: false }
      - { label: 'Couverture', name: 'couverture', widget: 'image', required: false }
      - { label: 'Categorie', name: 'category', widget: 'relation', collection: 'categories', value_field: "{{titre}}", display_fields: ["{{titre}}"], search_fields: ['titre'] }
      - { label: 'Annexes', name: 'annexes', widget: 'list', fields: [ { label: 'Title', name: 'titre', widget: 'string' }, { label: 'URL', name: 'url', widget: 'string' } ] }
      - { label: 'Corps du text', name: 'body', widget: 'markdown', required: false }
      - { label: 'Lettrine abilitata', name: 'enableDropCap', widget: 'boolean', required: false, default: false }

  - name: 'homepage'
    label: 'Homepage'
    folder: 'content/homepage'
    format: 'frontmatter'
    create: true
    identifier_field: name
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string', default: 'homepage' }
      - { label: 'Articolo in evidenza', name: 'vedette', widget: 'relation', collection: 'posts', value_field: "{{slug}}", display_fields: ["{{titre}}"], search_fields: ['titre'] }
      - { label: 'Articoli secondari', name: 'articles', widget: 'list', max: 6, min: 1, fields: [
          { label: 'Articolo', name: 'article', widget: 'relation', collection: 'posts', value_field: "{{slug}}", display_fields: ["{{titre}}"], search_fields: ['titre'] }
        ] }

  - name: 'publications'
    label: 'Publications'
    folder: 'content/publications'
    format: 'frontmatter'
    create: true
    identifier_field: titre
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'titre', widget: 'string' }
      - { label: 'Soustitre', name: 'soustitre', soustitre: 'string', required: false }
      - { label: 'Date', name: 'date', widget: 'datetime', date_format: true, time_format: false }
      - { label: 'URL', name: 'url', widget: 'string', required: false }
      - { label: 'Auteur', name: 'auteur', widget: 'string', required: false }
      - { label: 'Couverture', name: 'couverture', widget: 'image', required: false }
      - { label: 'Annexes', name: 'annexes', widget: 'list', fields: [ { label: 'Title', name: 'titre', widget: 'string' }, { label: 'URL', name: 'url', widget: 'string' } ] }
      - { label: 'Categorie', name: 'category', widget: 'relation', collection: 'publication-categories', value_field: "{{titre}}", display_fields: ["{{titre}}"], search_fields: ['titre'], required: false }
      - { label: 'Corps du text', name: 'body', widget: 'markdown', required: false }

  - name: 'institut'
    label: 'Institute'
    folder: 'content/institut'
    format: 'frontmatter'
    create: true
    identifier_field: titre
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'titre', widget: 'string' }
      - { label: 'Soustitre', name: 'soustitre', soustitre: 'string' }
      - { label: 'Ordre', name: 'ordre', widget: 'number' }
      - { label: 'Corps du text', name: 'body', widget: 'markdown' }

  - name: 'categories'
    label: 'Categories'
    folder: 'content/categories'
    format: 'frontmatter'
    create: true
    identifier_field: titre
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'titre', widget: 'string' }
      - { label: 'Ordre', name: 'ordre', widget: 'number' }
      - { label: 'Corps du text', name: 'body', widget: 'markdown' }

  - name: 'publication-categories'
    label: 'Publication Categories'
    folder: 'content/publication-categories'
    format: 'frontmatter'
    create: true
    identifier_field: titre
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'titre', widget: 'string' }
      - { label: 'Ordre', name: 'ordre', widget: 'number' }
      - { label: 'Couverture', name: 'couverture', widget: 'image', required: false }
      - { label: 'Corps du text', name: 'body', widget: 'markdown' }